package wp.src.main.java.com.example.wp.backend.service;

import java.util.List;
import java.util.Map;

public interface TouristAttractionsService {
    public List<Map<String, String>> findAllCategories();
    public Map<String, String> findCategoryByName(String name);
    public List<Map<String, String>> findAllBeaches();
    public List<Map<String, String>> findAllBeachesByCountry(String country);
    public Map<String, String> findBeachByName(String name);
    public List<Map<String, String>> findAllAmusementParks();
    public List<Map<String, String>> findAllAmusementParksByCountry(String country);
    public Map<String, String> findAmusementParkByName(String name);
    public List<Map<String, String>> findAllParks();
    public List<Map<String, String>> findAllParksByCountry(String country);
    public Map<String, String> findParkByName(String name);
    public List<Map<String, String>> findAllShowCaves();
    public List<Map<String, String>> findAllShowCavesByCountry(String country);
    public Map<String, String> findShowCaveByName(String name);
    public List<Map<String, String>> findAllTowers();
    public List<Map<String, String>> findAllTowersByCountry(String country);
    public Map<String, String> findTowerByName(String name);
    public List<Map<String, String>> findAllCastles();
    public List<Map<String, String>> findAllCastlesByCountry(String country);
    public Map<String, String> findCastleByName(String name);
    public List<Map<String, String>> findAllPalaces();
    public List<Map<String, String>> findAllPalacesByCountry(String country);
    public Map<String, String> findPalaceByName(String name);
    public List<Map<String, String>> findAllRoyalResidences();
    public List<Map<String, String>> findAllRoyalResidencesByCountry(String country);
    public Map<String, String> findRoyalResidenceByName(String name);
    public List<Map<String, String>> findAllMuseums();
    public List<Map<String, String>> findAllMuseumsByCountry(String country);
    public Map<String, String> findMuseumByName(String name);
    public List<Map<String, String>> findAllMonuments();
    public List<Map<String, String>> findAllMonumentsByCountry(String country);
    public Map<String, String> findMonumentByName(String name);
    public List<Map<String, String>> findAllBuildings();
    public List<Map<String, String>> findAllBuildingsByCountry(String country);
    public Map<String, String> findBuildingByName(String name);
    public List<Map<String, String>> findAllResorts();
    public List<Map<String, String>> findAllResortsByCountry(String country);
    public Map<String, String> findResortByName(String name);
    public List<Map<String, String>> findAllProtectedAreas();
    public List<Map<String, String>> findAllProtectedAreasByCountry(String country);
    public Map<String, String> findProtectedAreaByName(String name);
    public List<Map<String, String>> findAllNatureReserves();
    public List<Map<String, String>> findAllNatureReservesByCountry(String country);
    public Map<String, String> findNatureReserveByName(String name);
    public List<Map<String, String>> findAllHistoricDistricts();
    public List<Map<String, String>> findAllHistoricDistrictsByCountry(String country);
    public Map<String, String> findHistoricDistrictByName(String name);
    public List<Map<String, String>> findAllHeraldicSites();
    public List<Map<String, String>> findAllHeraldicSitesByCountry(String country);
    public Map<String, String> findHeraldicSiteByName(String name);
    public List<Map<String, String>> findAllUndergroundCities();
    public List<Map<String, String>> findAllUndergroundCitiesByCountry(String country);
    public List<Map<String, String>> findAllArchaeologicalSites();
    public List<Map<String, String>> findAllArchaeologicalSitesByCountry(String country);
    public Map<String, String> findArchaeologicalSiteByName(String name);
    public Map<String, String> findUndergroundCityByName(String name);
    public List<Map<String, String>> findAllNaturalArches();
    public List<Map<String, String>> findAllNaturalArchesByCountry(String country);
    public Map<String, String> findNaturalArchByName(String name);
    public List<Map<String, String>> findAllTriumphalArches();
    public List<Map<String, String>> findAllTriumphalArchesByCountry(String country);
    public Map<String, String> findTriumphalArchByName(String name);
    public List<Map<String, String>> findAlTownSquares();
    public Map<String, String> findTownSquareByName(String name);
    public List<Map<String, String>> findAllWaterfronts();
    public Map<String, String> findWaterfrontByName(String name);
    public List<Map<String, String>> findAllFountains();
    public Map<String, String> findFountainByName(String name);
    public List<Map<String, String>> findAllEntertainmentDistricts();
    public Map<String, String> findEntertainmentDistrictByName(String name);
    public List<Map<String, String>> findAllVisitorCenters();
    public Map<String, String> findVisitorCenterByName(String name);
    public List<Map<String, String>> findAllSpaceRelatedVisitorAttractions();
    public Map<String, String> findSpaceRelatedVisitorAttractionByName(String name);
}
